'
' Copyright © 2022 StreamNative
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'     http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
'

@startuml

skinparam defaultTextAlignment center

title Expiration

start
:receive\nstate;
switch (receive\nstate)
case (COMPLETED)
    if (expired ?) then (yes)
        #DDDDFF:tombstone\nstate;
        #DDFFDD:acknowledge\nstate;
    else (no)
        #FFDDDD:negative\nacknowledge\ntask;
    endif
case (FAILED)
    if (max\nattempts\nreached ?) then (yes)
        #DDFFDD:acknowledge\ntask;
    else (no)
        if (expired ?) then (yes)
            #DDDDFF:tombstone\nstate;
            #DDFFDD:acknowledge\nstate;
        else (no)
            #FFDDDD:negative\nacknowledge\ntask;
        endif
    endif
case (OTHER)
    #DDFFDD:acknowledge\nstate;
endswitch
end


@enduml