name: Tag Release

on: workflow_dispatch

jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Tag Release
        run: |
          ./mvnw -B versions:set -DremoveSnapshot
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          git commit -m "Release v$VERSION" -a
          git tag v$VERSION
          ./mvnw -B versions:set -DnextSnapshot
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          git commit -m "Next development version v$VERSION" -a
          git push
